Repository webpack-contrib/style-loader, pull requests merged in 2018-08, with the labels that each got.

#314 docs(readme): clarify `useable` usage
  README.md
Labels: pr_action: Review, priority: 5 (nice to have), semver: Patch, severity: 5 (confusing), type: Documentation

#338 fix(addStyles): use `var` instead of `const` (IE fix)
  lib/addStyles.js
Labels: semver: Patch, status: Approved, type: Bug

#341 feat(useable): add `insertInto` support (`options.insertInto`)
  test/useable.test.js
  useable.js
Labels: semver: Minor, status: Approved, type: Feature

#342 chore(package): update `schema-utils` v0.4.5...1.0.0 (`dependencies`)
  package-lock.json
  package.json
Labels: semver: Patch, status: Approved, type: Chore
